# Generated by Django 3.0.2 on 2021-02-25 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='题干')),
                ('question_type', models.CharField(max_length=10, verbose_name='题目类型')),
                ('answer', models.TextField(verbose_name='答案')),
                ('difficulty', models.CharField(max_length=10, verbose_name='难度')),
                ('score', models.IntegerField(default=1, verbose_name='分值')),
                ('applyto', models.CharField(default='', max_length=32, verbose_name='适合人员')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
            },
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.CharField(max_length=40, unique=True, verbose_name='试卷名称')),
                ('test_time', models.IntegerField(help_text='单位是分钟', verbose_name='考试时长')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('create_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='出题人')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='WrongRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_times', models.IntegerField(default=0, verbose_name='错误次数')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.TestPaper', verbose_name='试卷')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.QuestionBank', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(verbose_name='成绩')),
                ('test_time', models.DateTimeField(auto_now_add=True, verbose_name='考试时间')),
                ('papername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.TestPaper', verbose_name='考试科目')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '成绩表',
                'verbose_name_plural': '成绩表',
            },
        ),
        migrations.AddField(
            model_name='questionbank',
            name='pid',
            field=models.ManyToManyField(blank=True, null=True, to='exam.TestPaper', verbose_name='所属试卷'),
        ),
    ]
