# Generated by Django 3.0.2 on 2021-02-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20210225_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='difficulty',
            field=models.IntegerField(choices=[(0, '简单'), (1, '中等'), (2, '难')], verbose_name='难度'),
        ),
    ]
