# Generated by Django 3.0.2 on 2021-02-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_remove_questionbank_applyto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wrongrecord',
            options={'verbose_name': '错题集', 'verbose_name_plural': '错题集'},
        ),
        migrations.AddField(
            model_name='wrongrecord',
            name='my_ans',
            field=models.TextField(default='', verbose_name='我的答案'),
        ),
    ]
