# Generated by Django 3.0.2 on 2021-02-26 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0005_auto_20210226_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='题库名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
                ('create_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '题库信息',
                'verbose_name_plural': '题库信息',
            },
        ),
        migrations.AddField(
            model_name='questionbank',
            name='question_bank_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.QuestionInfo'),
        ),
    ]
