# Generated by Django 3.0.2 on 2021-03-11 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210306_0042'),
        ('exam', '0007_testpaper_hot_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioninfo',
            name='applyto',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Units', verbose_name='适用人员'),
        ),
    ]
