# Generated by Django 3.0.2 on 2021-03-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210306_0042'),
        ('exam', '0008_questioninfo_applyto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioninfo',
            name='applyto',
        ),
        migrations.AddField(
            model_name='questioninfo',
            name='applyto',
            field=models.ManyToManyField(blank=True, default='', null=True, to='users.Units', verbose_name='适用人员'),
        ),
    ]
