# Generated by Django 3.0.2 on 2021-03-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210306_0042'),
        ('exam', '0010_auto_20210311_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='applyto',
            field=models.ManyToManyField(blank=True, null=True, to='users.Units', verbose_name='适用人员'),
        ),
    ]
