# Generated by Django 3.0.2 on 2021-03-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_trainrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainrecord',
            name='title',
            field=models.CharField(default='', max_length=128, verbose_name='训练科目'),
        ),
        migrations.AlterField(
            model_name='trainrecord',
            name='train_type',
            field=models.CharField(max_length=256, verbose_name='训练内容'),
        ),
    ]
