# Generated by Django 3.0.2 on 2021-03-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_auto_20210318_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainrecord',
            name='starttime',
            field=models.DateTimeField(blank=True, default='2000-01-01 00:00:00', null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='trainrecord',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='开始时间'),
        ),
    ]
