# Generated by Django 3.0.2 on 2021-03-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20210328_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='is_random',
            field=models.IntegerField(choices=[(0, '固定出庭'), (1, '随机出题')], default=0, verbose_name='是否随机'),
        ),
    ]
