# Generated by Django 3.0.2 on 2021-03-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_testpaper_is_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='ans_count',
            field=models.IntegerField(default=0, verbose_name='问答数量'),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='fillin_count',
            field=models.IntegerField(default=0, verbose_name='填空数量'),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='judge_count',
            field=models.IntegerField(default=0, verbose_name='判断数量'),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='multi_count',
            field=models.IntegerField(default=0, verbose_name='多选数量'),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='singel_count',
            field=models.IntegerField(default=0, verbose_name='单选数量'),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='is_random',
            field=models.IntegerField(choices=[(0, '固定出题'), (1, '随机出题')], default=0, verbose_name='是否随机'),
        ),
    ]
