# Generated by Django 3.0.2 on 2021-03-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_auto_20210330_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioninfo',
            name='blongs_to_paper',
            field=models.ManyToManyField(blank=True, default='', null=True, to='exam.TestPaper', verbose_name='所属试卷'),
        ),
    ]
