# Generated by Django 3.0.2 on 2021-03-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_questioninfo_blongs_to_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioninfo',
            name='blongs_to_paper',
        ),
        migrations.AddField(
            model_name='testpaper',
            name='blongs_to_paper',
            field=models.ManyToManyField(blank=True, default='', null=True, to='exam.QuestionInfo', verbose_name='所属试卷'),
        ),
    ]
