# Generated by Django 3.0.2 on 2021-03-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_auto_20210330_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='chance_times',
            field=models.IntegerField(default=0, verbose_name='可考次数'),
        ),
    ]
