# Generated by Django 3.0.2 on 2021-04-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_testpaper_chance_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
    ]
