# Generated by Django 3.0.2 on 2021-04-01 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0022_record_is_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('is_handled', models.BooleanField(default=False, verbose_name='处理')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.TestPaper', verbose_name='试卷')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
        ),
    ]
