# Generated by Django 3.0.2 on 2021-04-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0023_proposalrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalrecord',
            options={'verbose_name': '考试申请记录', 'verbose_name_plural': '考试申请记录'},
        ),
    ]
