# Generated by Django 3.0.2 on 2021-02-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=32, verbose_name='含正则的URL')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
            ],
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='角色名称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, to='users.Role', verbose_name='拥有的所有角色'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(to='users.Permission', verbose_name='拥有的所有权限'),
        ),
    ]
