# Generated by Django 3.0.2 on 2021-02-28 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210228_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='icon',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='图标'),
        ),
        migrations.AddField(
            model_name='menus',
            name='title',
            field=models.CharField(default='', max_length=32, verbose_name='菜单'),
        ),
        migrations.AddField(
            model_name='permission',
            name='menu',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Menus', verbose_name='所属菜单'),
        ),
    ]
