# Generated by Django 3.0.2 on 2021-02-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210228_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='parent',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Permission', verbose_name='父节点'),
        ),
        migrations.AddField(
            model_name='permission',
            name='url_type',
            field=models.IntegerField(blank=True, choices=[(0, '菜单'), (1, '按钮'), (2, '链接')], default=0, null=True, verbose_name='url类型'),
        ),
    ]
