# Generated by Django 3.0.2 on 2021-02-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_permission_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='menu',
        ),
    ]
