# Generated by Django 3.0.2 on 2021-03-05 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_permission_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='sequence',
            field=models.IntegerField(default=0, verbose_name='菜单序号'),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Menus', verbose_name='是否菜单'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='title',
            field=models.CharField(max_length=32, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url_type',
            field=models.IntegerField(blank=True, choices=[(0, '菜单'), (1, '按钮'), (2, '链接')], default='', null=True, verbose_name='url类型'),
        ),
    ]
