# Generated by Django 3.0.2 on 2021-03-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210305_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='layer',
            field=models.IntegerField(choices=[(0, '一级菜单'), (1, '二级菜单'), (2, '三级菜单'), (3, '四级菜单')], default=0, verbose_name='菜单级别'),
        ),
    ]
