# Generated by Django 3.0.2 on 2021-03-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('users', '0013_auto_20210306_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='is_menu',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='role',
            name='menus',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, to='rbac.Role', verbose_name='拥有的所有角色'),
        ),
        migrations.DeleteModel(
            name='Menus',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
