# Generated by Django 3.0.2 on 2021-03-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_userprofile_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='姓名'),
        ),
        migrations.AlterUniqueTogether(
            name='units',
            unique_together={('unit_full_name', 'unit_name')},
        ),
    ]
