# Generated by Django 3.0.2 on 2021-04-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210316_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='idcard',
            field=models.CharField(blank=True, default='', max_length=18, null=True, verbose_name='身份证号'),
        ),
    ]
