# Generated by Django 3.0.2 on 2021-04-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210404_2319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='units',
            unique_together={('uname2', 'unit_name')},
        ),
    ]
